### ISSUE TITLE
Touch and Button block bugs

### ISSUE THREAD

**Issue by brendonhatcher** [OttoDIY/blockly#111]
OttoBlockly 1.4.3

In the Sensing group is a Touch block.
The block defaults to PIN 2 even though the sensor is attached to A0 (according to the "Getting started with Otto DIY robots" presentation).
It would be simpler for users if it defaulted to A0.

The block contains a checkbox.
I think an empty checkbox means "not pressed" and checked means "pressed".
However, the code is inverted:

Empty checkbox: digitalRead(A0);
Ticked checkbox: (!digitalRead(A0));

The same is true of the Button block.

Finally, the tick in the checkbox is inconsistent.
Sometimes it shows a tick, and sometimes an offset black square.

![touch bug](https://user-images.githubusercontent.com/61579046/132504103-7c219113-6dfa-4c8c-adae-1bd04d83cf9b.PNG)

**Comment by cparrapa** [comment]
Good points @brendonhatcher 
We will update the defaults the got lost in the dropdown conversion of pins.

Thanks for your feedback we will be fixing these stuff.

**Comment by cparrapa** [comment]
![image](https://user-images.githubusercontent.com/8412468/133514997-3813aad0-02c1-4e91-9e28-cc30d277828c.png)
Hi @brendonhatcher 
What do you think of something like this?

**Comment by brendonhatcher** [comment]
A0 for touch is good.  I don't see a button in the standard build or any of the modular add-ons, so I can't comment on that.
I'm neutral on the finger pressing icon vs the word "pressed".
The checkbox should still be a tick or a blank, because that is more in keeping with standard web form UI.

**Comment by cparrapa** [comment]
Hi @brendonhatcher 

Thanks for the feedback, we actually are testing buttons as an alternative to the touch that sometimes is not so reliable. What we want is to have A0 as the pin to swap multiple sensors in Otto so that you can test all kinds of interactions by changing components what do you think?
At least now with the finger press the meaning is now in line with the code since means if the button is on hold or not.
We will updated the check box to tick makes sense

**Comment by brendonhatcher** [comment]
That approach sounds good!

**Comment by cparrapa** [comment]
fixed here https://github.com/OttoDIY/blockly/commit/e68532c32e563b06385c25dc819042a98d450e55
