### ISSUE TITLE
Escornabot blocks

### ISSUE THREAD

**Issue by NeftaliVenancio** [OttoDIY/blockly#139]
_Si no mal recuerdo había una categoría de bloques dedicada al escornabot. ¿Hay planes de integrar bloques relacionados nuevamente?_ 

If I remember correctly there was a category of blocks dedicated to the scornabot. Are there plans to integrate related blocks again?

**Comment by BodoMinea** [comment]
It's best to write issues in English.

I see that the code regarding the escornabot is still here - https://github.com/OttoDIY/blockly/blob/master/www/blocs%26generateurs/escornabot.js

**Comment by BodoMinea** [comment]
I haven't worked on the project in a while and don't know why the blocks won't show up. Last time I used Blockly there was an option to select block visibility based on a category checklist, I see that's gone and replaced with the three complexity levels in the menu bar. 

Maybe the blocks you are looking for disappeared during this change somehow?

**Comment by BodoMinea** [comment]
At the very basic level it seems that the Escornabot blocks are not shown because they are not present in the XML loaded from https://github.com/OttoDIY/blockly/tree/master/www/toolbox

(toolbox_master.xml has them but doesn't have the „level” based separation, toolbox_arduino_all.xml seems to be the default one and is completely missing these blocks)

I don't know if that's because some recently arisen compatibility issue, I'll let someone more familiar with the project's recent development look into it.

**Comment by cparrapa** [comment]
Hi @NeftaliVenancio  @BodoMinea 
Yes we forgot to unhide it from the toolbar in the next release we will add again for level 3
Thanks

**Comment by cparrapa** [comment]
https://github.com/OttoDIY/blockly/commits/master
